# Stage 1: Build Flutter App
FROM debian:latest AS build-env
  
  # Install required dependencies
RUN apt-get update && \
apt-get install -y curl git unzip
  
  # Set environment variables
ARG FLUTTER_SDK=/usr/local/flutter
ARG FLUTTER_VERSION=3.1.4
ARG APP=/app/
  
  # Clone Flutter repository
RUN git clone https://github.com/flutter/flutter.git $FLUTTER_SDK
  
  # Change directory to Flutter folder and checkout the specific version
RUN cd $FLUTTER_SDK && git fetch && git checkout $FLUTTER_VERSION
  
  # Setup Flutter path as an environmental variable
ENV PATH="$FLUTTER_SDK/bin:$FLUTTER_SDK/bin/cache/dart-sdk/bin:${PATH}"
  
  # Run Flutter doctor to check installation
RUN flutter doctor -v
  
  # Create folder to copy source code
RUN mkdir $APP
  
  # Copy source code to the folder
COPY . $APP
  
  # Change working directory
WORKDIR $APP
  
  # Run Flutter commands: clean, pub get, build web
RUN flutter clean && flutter pub get && flutter build web
  
  # Stage 2: Deploy with Nginx
FROM nginx:1.25.2-alpine
  
  # Copy the built web app from the first stage to Nginx
COPY --from=build-env $APP/build/web /usr/share/nginx/html
  
  # Expose and run Nginx
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
